# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currency_exchange_fapi_client.models.user_creation_error_response import UserCreationErrorResponse

class TestUserCreationErrorResponse(unittest.TestCase):
    """UserCreationErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserCreationErrorResponse:
        """Test UserCreationErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserCreationErrorResponse`
        """
        model = UserCreationErrorResponse()
        if include_optional:
            return UserCreationErrorResponse(
                errors = {
                    'key' : [
                        ''
                        ]
                    }
            )
        else:
            return UserCreationErrorResponse(
                errors = {
                    'key' : [
                        ''
                        ]
                    },
        )
        """

    def testUserCreationErrorResponse(self):
        """Test UserCreationErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
