# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currency_exchange_fapi_client.api.auth_api import AuthApi


class TestAuthApi(unittest.IsolatedAsyncioTestCase):
    """AuthApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AuthApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_auth_create_token(self) -> None:
        """Test case for auth_create_token

        Create Token
        """
        pass

    async def test_auth_create_user(self) -> None:
        """Test case for auth_create_user

        Create User
        """
        pass

    async def test_auth_refresh_access_token(self) -> None:
        """Test case for auth_refresh_access_token

        Refresh Access Token
        """
        pass

    async def test_auth_revoke_users_token(self) -> None:
        """Test case for auth_revoke_users_token

        Revoke Users Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
