# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currency_exchange_fapi_client.models.transition_users_categories import TransitionUsersCategories

class TestTransitionUsersCategories(unittest.TestCase):
    """TransitionUsersCategories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransitionUsersCategories(self):
        """Test TransitionUsersCategories"""
        # inst = TransitionUsersCategories()

if __name__ == '__main__':
    unittest.main()
