# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currency_exchange_fapi_client.api.currency_exchange_api import CurrencyExchangeApi


class TestCurrencyExchangeApi(unittest.IsolatedAsyncioTestCase):
    """CurrencyExchangeApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CurrencyExchangeApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_currency_exchange_add_currency(self) -> None:
        """Test case for currency_exchange_add_currency

        Add Currency
        """
        pass

    async def test_currency_exchange_add_exchange_rate(self) -> None:
        """Test case for currency_exchange_add_exchange_rate

        Add Exchange Rate
        """
        pass

    async def test_currency_exchange_convert_currencies(self) -> None:
        """Test case for currency_exchange_convert_currencies

        Convert Currencies
        """
        pass

    async def test_currency_exchange_delete_currency(self) -> None:
        """Test case for currency_exchange_delete_currency

        Delete Currency
        """
        pass

    async def test_currency_exchange_delete_exchange_rate(self) -> None:
        """Test case for currency_exchange_delete_exchange_rate

        Delete Exchange Rate
        """
        pass

    async def test_currency_exchange_get_all_currencies(self) -> None:
        """Test case for currency_exchange_get_all_currencies

        Get All Currencies
        """
        pass

    async def test_currency_exchange_get_all_exchange_rates(self) -> None:
        """Test case for currency_exchange_get_all_exchange_rates

        Get All Exchange Rates
        """
        pass

    async def test_currency_exchange_get_currency(self) -> None:
        """Test case for currency_exchange_get_currency

        Get Currency
        """
        pass

    async def test_currency_exchange_get_exchange_rate(self) -> None:
        """Test case for currency_exchange_get_exchange_rate

        Get Exchange Rate
        """
        pass

    async def test_currency_exchange_update_currency(self) -> None:
        """Test case for currency_exchange_update_currency

        Update Currency
        """
        pass

    async def test_currency_exchange_update_exchange_rate(self) -> None:
        """Test case for currency_exchange_update_exchange_rate

        Update Exchange Rate
        """
        pass


if __name__ == '__main__':
    unittest.main()
