# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currency_exchange_fapi_client.models.user_created_response import UserCreatedResponse

class TestUserCreatedResponse(unittest.TestCase):
    """UserCreatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserCreatedResponse:
        """Test UserCreatedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserCreatedResponse`
        """
        model = UserCreatedResponse()
        if include_optional:
            return UserCreatedResponse(
                username = '',
                category = 'API_CLIENT',
                is_active = True,
                id = 56
            )
        else:
            return UserCreatedResponse(
                username = '',
                id = 56,
        )
        """

    def testUserCreatedResponse(self):
        """Test UserCreatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
