# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currency_exchange_fapi_client.api.users_api import UsersApi


class TestUsersApi(unittest.IsolatedAsyncioTestCase):
    """UsersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UsersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_users_downgrade_users_category(self) -> None:
        """Test case for users_downgrade_users_category

        Downgrade Users Category
        """
        pass

    async def test_users_get_all_users(self) -> None:
        """Test case for users_get_all_users

        Get All Users
        """
        pass

    async def test_users_get_user(self) -> None:
        """Test case for users_get_user

        Get User
        """
        pass

    async def test_users_make_user_active(self) -> None:
        """Test case for users_make_user_active

        Make User Active
        """
        pass

    async def test_users_make_user_inactive(self) -> None:
        """Test case for users_make_user_inactive

        Make User Inactive
        """
        pass

    async def test_users_promote_users_category(self) -> None:
        """Test case for users_promote_users_category

        Promote Users Category
        """
        pass


if __name__ == '__main__':
    unittest.main()
