# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currency_exchange_fapi_client.models.exchange_rate_out_schema import ExchangeRateOutSchema

class TestExchangeRateOutSchema(unittest.TestCase):
    """ExchangeRateOutSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExchangeRateOutSchema:
        """Test ExchangeRateOutSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExchangeRateOutSchema`
        """
        model = ExchangeRateOutSchema()
        if include_optional:
            return ExchangeRateOutSchema(
                id = 56,
                base_currency = currency_exchange_fapi_client.models.currency_out_schema.CurrencyOutSchema(
                    id = 56, 
                    name = '', 
                    code = 'AEI', 
                    sign = '', ),
                target_currency = currency_exchange_fapi_client.models.currency_out_schema.CurrencyOutSchema(
                    id = 56, 
                    name = '', 
                    code = 'AEI', 
                    sign = '', ),
                rate = 1.337
            )
        else:
            return ExchangeRateOutSchema(
                id = 56,
                base_currency = currency_exchange_fapi_client.models.currency_out_schema.CurrencyOutSchema(
                    id = 56, 
                    name = '', 
                    code = 'AEI', 
                    sign = '', ),
                target_currency = currency_exchange_fapi_client.models.currency_out_schema.CurrencyOutSchema(
                    id = 56, 
                    name = '', 
                    code = 'AEI', 
                    sign = '', ),
                rate = 1.337,
        )
        """

    def testExchangeRateOutSchema(self):
        """Test ExchangeRateOutSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
