# coding: utf-8

# flake8: noqa

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "CurrencyExchangeApi",
    "AuthApi",
    "UsersApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccessExpiresIn",
    "ConvertedCurrencySchema",
    "CurrencyOutSchema",
    "ExchangeRateOutSchema",
    "HTTPValidationError",
    "RefreshExpiresIn",
    "TokenCreatedResponse",
    "TokensRevokedResponse",
    "TransitionUsersCategories",
    "UserCategory",
    "UserCreatedResponse",
    "UserCreationErrorResponse",
    "UserOut",
    "ValidationError",
    "ValidationErrorLocInner",
]

# import apis into sdk package
from currency_exchange_fapi_client.api.currency_exchange_api import CurrencyExchangeApi
from currency_exchange_fapi_client.api.auth_api import AuthApi
from currency_exchange_fapi_client.api.users_api import UsersApi

# import ApiClient
from currency_exchange_fapi_client.api_response import ApiResponse
from currency_exchange_fapi_client.api_client import ApiClient
from currency_exchange_fapi_client.configuration import Configuration
from currency_exchange_fapi_client.exceptions import OpenApiException
from currency_exchange_fapi_client.exceptions import ApiTypeError
from currency_exchange_fapi_client.exceptions import ApiValueError
from currency_exchange_fapi_client.exceptions import ApiKeyError
from currency_exchange_fapi_client.exceptions import ApiAttributeError
from currency_exchange_fapi_client.exceptions import ApiException

# import models into sdk package
from currency_exchange_fapi_client.models.access_expires_in import AccessExpiresIn
from currency_exchange_fapi_client.models.converted_currency_schema import ConvertedCurrencySchema
from currency_exchange_fapi_client.models.currency_out_schema import CurrencyOutSchema
from currency_exchange_fapi_client.models.exchange_rate_out_schema import ExchangeRateOutSchema
from currency_exchange_fapi_client.models.http_validation_error import HTTPValidationError
from currency_exchange_fapi_client.models.refresh_expires_in import RefreshExpiresIn
from currency_exchange_fapi_client.models.token_created_response import TokenCreatedResponse
from currency_exchange_fapi_client.models.tokens_revoked_response import TokensRevokedResponse
from currency_exchange_fapi_client.models.transition_users_categories import TransitionUsersCategories
from currency_exchange_fapi_client.models.user_category import UserCategory
from currency_exchange_fapi_client.models.user_created_response import UserCreatedResponse
from currency_exchange_fapi_client.models.user_creation_error_response import UserCreationErrorResponse
from currency_exchange_fapi_client.models.user_out import UserOut
from currency_exchange_fapi_client.models.validation_error import ValidationError
from currency_exchange_fapi_client.models.validation_error_loc_inner import ValidationErrorLocInner
